In [62]:
import numpy as np
import pandas as pd

In [65]:

df = pd.read_csv(open('spam.csv', encoding='ISO-8859-1'))
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [66]:
df.tail()

v1                                                 v2 Unnamed: 2  \
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [68]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [71]:
Sp = pd.get_dummies(df['v1'])
Sp


ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [87]:

from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()


label = le.fit_transform(df['v1'])

label


array([0, 0, 1, ..., 0, 0, 0])

In [88]:

df.drop("v1", axis=1, inplace=True)


df["v1"] = label

# printing Dataframe
df


v2 Unnamed: 2 Unnamed: 3  \
0     Go until jurong point, crazy.. Available only ...        NaN        NaN   
1                         Ok lar... Joking wif u oni...        NaN        NaN   
2     Free entry in 2 a wkly comp to win FA Cup fina...        NaN        NaN   
3     U dun say so early hor... U c already then say...        NaN        NaN   
4     Nah I don't think he goes to usf, he lives aro...        NaN        NaN   
...                                                 ...        ...        ...   
5567  This is the 2nd time we have tried 2 contact u...        NaN        NaN   
5568              Will Ì_ b going to esplanade fr home?        NaN        NaN   
5569  Pity, * was in mood for that. So...any other s...        NaN        NaN   
5570  The guy did some bitching but I acted like i'd...        NaN        NaN   
5571                         Rofl. Its true to its name        NaN        NaN   

     Unnamed: 4  v1  
0           NaN   0  
1           NaN   0  
2           NaN   1  
3           NaN   0  
4           NaN   0  
...         ...  ..  
5567        NaN   1  
5568        NaN   0  
5569        NaN   0  
5570        NaN   0  
5571        NaN   0  

[5572 rows x 5 columns]

In [94]:
df.head()

v2 Unnamed: 2 Unnamed: 3  \
0  Go until jurong point, crazy.. Available only ...        NaN        NaN   
1                      Ok lar... Joking wif u oni...        NaN        NaN   
2  Free entry in 2 a wkly comp to win FA Cup fina...        NaN        NaN   
3  U dun say so early hor... U c already then say...        NaN        NaN   
4  Nah I don't think he goes to usf, he lives aro...        NaN        NaN   

  Unnamed: 4  v1  
0        NaN   0  
1        NaN   0  
2        NaN   1  
3        NaN   0  
4        NaN   0

In [95]:
train_set = df.iloc[:,4:5].values
train_set

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [96]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
scaled_tr = sc.fit_transform(train_set)
scaled_tr


array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [98]:
scaled_tr[60-60:60,0]

array([0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0.])

In [99]:
x_train = []
y_train = []

for i in range(60,1258):
  x_train.append(scaled_tr[i-60:i,0])
  y_train.append(scaled_tr[i,0])

In [100]:
x_train

[array([0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 1., 0., 0., 0., 0.]),
 array([1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0.

In [101]:
y_train

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0

In [102]:
x_train,y_train = np.array(x_train),np.array(y_train)

In [103]:
x_train

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [104]:
x_train.shape

(1198, 60)

In [105]:
x_train = np.reshape(x_train,(1198, 60, 1))
x_train.shape

(1198, 60, 1)

In [106]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [107]:
model = Sequential()
model.add(LSTM(50, input_shape = (60,1),return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(Dense(1))

In [108]:
model.compile(optimizer='adam',loss='mse')

In [110]:
model.fit(x_train,y_train,epochs=24,batch_size=32)

Epoch 1/24
38/38 [==============================] - 4s 115ms/step - loss: 0.1265
Epoch 2/24
38/38 [==============================] - 4s 116ms/step - loss: 0.1264
Epoch 3/24
38/38 [==============================] - 4s 117ms/step - loss: 0.1265
Epoch 4/24
38/38 [==============================] - 4s 116ms/step - loss: 0.1263
Epoch 5/24
38/38 [==============================] - 4s 116ms/step - loss: 0.1261
Epoch 6/24
38/38 [==============================] - 4s 117ms/step - loss: 0.1264
Epoch 7/24
38/38 [==============================] - 4s 116ms/step - loss: 0.1263
Epoch 8/24
38/38 [==============================] - 5s 119ms/step - loss: 0.1261
Epoch 9/24
38/38 [==============================] - 4s 116ms/step - loss: 0.1263
Epoch 10/24
38/38 [==============================] - 4s 117ms/step - loss: 0.1265
Epoch 11/24
38/38 [==============================] - 4s 116ms/step - loss: 0.1262
Epoch 12/24
38/38 [==============================] - 4s 117ms/step - loss: 0.1261
Epoch 13/24
38/38 [======

In [111]:
model.save('ARK.h5')